<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\Icons\Activity\activity_white.png" />
    <None Remove="Resources\Images\Icons\Briefcase\briefcase_white.png" />
    <None Remove="Resources\Images\Icons\Calendar\calendar_white.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeetleUI\BeetleUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\Icons\Activity\activity_white.png" />
    <Resource Include="Resources\Images\Icons\Briefcase\briefcase_white.png" />
    <Resource Include="Resources\Images\Icons\Calendar\calendar_white.png" />
  </ItemGroup>

</Project>
