<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\Icons\Activity\activity_white.png" />
    <None Remove="Resources\Images\Icons\Arrow-Left-Circle\arrow-left-circle_black.png" />
    <None Remove="Resources\Images\Icons\Book-Open\book-open_black.png" />
    <None Remove="Resources\Images\Icons\Book\book_black.png" />
    <None Remove="Resources\Images\Icons\Briefcase\briefcase_white.png" />
    <None Remove="Resources\Images\Icons\Calendar\calendar_white.png" />
    <None Remove="Resources\Images\Icons\Edit-3\edit-3_black.png" />
    <None Remove="Resources\Images\Icons\Trash\trash._blacksvg.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeetleUI\BeetleUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\Icons\Activity\activity_white.png" />
    <Resource Include="Resources\Images\Icons\Arrow-Left-Circle\arrow-left-circle_black.png" />
    <Resource Include="Resources\Images\Icons\Book-Open\book-open_black.png" />
    <Resource Include="Resources\Images\Icons\Book\book_black.png" />
    <Resource Include="Resources\Images\Icons\Briefcase\briefcase_white.png" />
    <Resource Include="Resources\Images\Icons\Calendar\calendar_white.png" />
    <Resource Include="Resources\Images\Icons\Edit-3\edit-3_black.png" />
    <Resource Include="Resources\Images\Icons\Trash\trash_black.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
